-- 1)Montar o create das tabelas do diagrama, incluindo o create das FK e PK.
CREATE TABLE CIDADE (
ID INT IDENTITY(1,1) PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
UF VARCHAR(2)
);

CREATE TABLE FUNCIONARIO(
ID INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(150) NOT NULL,
	NUMERO VARCHAR(5),
	BAIRRO VARCHAR(100),
	ID_CIDADE INT
	FOREIGN KEY (ID_CIDADE) REFERENCES CIDADE(ID)
);

CREATE TABLE CLIENTE (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	NUMERO VARCHAR(5),
	BAIRRO VARCHAR(100),
	ID_CIDADE INT,
	EMAIL VARCHAR(150),
	TELEFONE VARCHAR(15),
	CELULAR VARCHAR(15),
	DATACADASTRO DATETIME
	FOREIGN KEY (ID_CIDADE) REFERENCES CIDADE(ID)
);

CREATE TABLE VENDA (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	ID_CLIENTE INT FOREIGN KEY REFERENCES CLIENTE(ID),
	ID_FUNCIONARIO INT FOREIGN KEY REFERENCES FUNCIONARIO(ID),
	DATA_VENDA DATETIME NOT NULL
);

CREATE TABLE PRODUTO (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	DESCRICAO VARCHAR(100) NOT NULL,
	VALOR DECIMAL(10,2) NOT NULL
);

CREATE TABLE VENDA_ITENS (
	ID_VENDA INT FOREIGN KEY REFERENCES VENDA(ID),
	ID_PRODUTO INT FOREIGN KEY REFERENCES PRODUTO(ID),
	QTD INT
);

-- 2)Montar um relatório que traga o total das vendas realizado no estado de SP no período de 01/08/2022 até 10/08/2022
SELECT SUM(P.VALOR * I.QTD) AS TOTAL_VENDAS_SP
FROM VENDA V
JOIN VENDA_ITENS I ON V.ID = I.ID_VENDA
JOIN PRODUTO P ON i.ID_PRODUTO = P.ID
JOIN CLIENTE C ON V.ID_CLIENTE = C.ID
JOIN CIDADE CD ON C.ID_CIDADE = CD.ID
WHERE CD.UF = 'SP' AND V.DATA_VENDA BETWEEN '01/08/2022' AND '10/08/2022';

-- 3)Para melhorar a performance criar um índice na coluna estado 
CREATE INDEX IDX_CIDADE_UF ON CIDADE (UF);

-- 4)Montar uma query que retorne os funcionários que bateram a meta de vendas, acima de R$ 100.000,00 no mês de agosto ordenando pelo total das vendas
SELECT F.ID, F.NOME, SUM(VI.QTD * P.VALOR) AS TOTAL_VENDAS
FROM FUNCIONARIO F
INNER JOIN VENDA V ON F.ID = V.ID_FUNCIONARIO
INNER JOIN VENDA_ITENS VI ON V.ID = VI.ID_VENDA
INNER JOIN PRODUTO P ON VI.ID_PRODUTO = P.ID
WHERE MONTH(V.DATA_VENDA) = 8 AND YEAR(V.DATA_VENDA) = YEAR(GETDATE())
GROUP BY F.ID, F.NOME
HAVING SUM(VI.QTD * P.VALOR) >= 100000
ORDER BY TOTAL_VENDAS DESC;

-- 5)Qual o comando que retorna todos os comandos que estão sendo executados no momento pelo SQL Server?
sp_who2;