CREATE TABLE CIDADE (
ID INT IDENTITY(1,1) PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
UF VARCHAR(2)
);

CREATE TABLE FUNCIONARIO(
ID INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(150) NOT NULL,
	NUMERO VARCHAR(5),
	BAIRRO VARCHAR(100),
	ID_CIDADE INT
	FOREIGN KEY (ID_CIDADE) REFERENCES CIDADE(ID)
);

CREATE TABLE CLIENTE (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	NUMERO VARCHAR(5),
	BAIRRO VARCHAR(100),
	ID_CIDADE INT,
	EMAIL VARCHAR(150),
	TELEFONE VARCHAR(15),
	CELULAR VARCHAR(15),
	DATACADASTRO DATETIME
	FOREIGN KEY (ID_CIDADE) REFERENCES CIDADE(ID)
);

CREATE TABLE VENDA (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	ID_CLIENTE INT FOREIGN KEY REFERENCES CLIENTE(ID),
	ID_FUNCIONARIO INT FOREIGN KEY REFERENCES FUNCIONARIO(ID),
	DATA_VENDA DATETIME NOT NULL
);

CREATE TABLE PRODUTO (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	DESCRICAO VARCHAR(100) NOT NULL,
	VALOR DECIMAL(10,2) NOT NULL
);

CREATE TABLE VENDA_ITENS (
	ID_VENDA INT FOREIGN KEY REFERENCES VENDA(ID),
	ID_PRODUTO INT FOREIGN KEY REFERENCES PRODUTO(ID),
	QTD INT
);